spring:
  application:
    name: spoton-backend
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

server:
  port: 8181

jwt:
  acc:
    expiration: 30
    secretKey: ${ACC_KEY}
  rf:
    expiration: 14400
    secretKey: ${RF_KEY}