spring:
  application:
    name: spoton-backend
  # ??? ??? ??
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  # redis ??
  data:
    redis:
      host: localhost
      port: 6379
  # ??? ?? ??
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  # ??? ??? ??
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${FROM_MAIL}
    password: ${MAIL_TOKEN}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          # kakao OAuth2 ??
          kakao:
            client-id: ${KAKAO_APPKEY}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email

          # naver OAuth2 ??
          naver:
            client-id: ${NAVER_APPKEY}
            client-secret: ${NAVER_SECRET}
            redirect-uri: ${NAVER_REDIRECT}
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - profile_image
              - email
        provider:
          # kakao OAuth2 Provider ??
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          # naver OAuth2 Provider ??
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8181

# jwt ??
jwt:
  acc:
    expiration: 30
    secretKey: ${ACC_KEY}
  rf:
    expiration: 14400
    secretKey: ${RF_KEY}

# log ??
logging:
  level:
    org:
      springframework:
        security: DEBUG

