name: Backend Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository Code Load
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml create
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-prod.yml

      - name: test and build
        run: ./gradlew clean build

      - name: AWS credentials setting (for Access AWS Resource)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Image create
        run: docker build -t spoton-server .

      - name: Docker image add tag
        run: docker tag spoton-server spoton-server:latest

      - name: Docker Image Push to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/spoton-server:latest

      - name: SSH - EC2 access
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd spoton/ || exit 1
            docker-compose down -v || true
            docker rmi spoton-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/spoton-server:latest
            docker-compose up -d